### ISSUE TITLE
Try and remove `Box`ing wherever possible within the render_callback builder method.

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/coreaudio-rs#10]
There's a lot of boxing going on - all of which should be theoretically unnecessary given that we're sharing the stack with the C code, not sending stuff to it.

It might be easier to address this once the Fn/FnMut/FnOnce trait implementations are stabilised.

**Comment by yupferris** [comment]
I don't think we can get away with not `Box`ing at least once, since we need to store the `FnMut` on the heap when giving it to Core Audio.

Currently, the second `Box` is necessary because the `FnMut` and its closure together make a fat pointer, so it doesn't fit into a single `Box`. Perhaps that will be better as those traits are stabilized though, as you mention.

As for the `Box` in the `render_callback` function itself, that may not be necessary (it might be though, because I don't think `FnMut` implements `Sized`). But we need to `Box` internally at least.
